Implementing Styling for Components
JohannSiemens/capstone-project pull request #17
Opened 2023-06-07 10:44 UTC by JohannSiemens

[User Story](https://github.com/JohannSiemens/capstone-project/issues/16)

Decided to keep the styling small and only implemented the basics for the first "Workout" screen.

**Not done, open for next US:**
- Implementation of styling for further screens
- Refactoring of editing state (also in the workout screen) still needed
- Accessibility is also going to be part of a different US

2023-06-07 13:08 UTC, doemser requested changes
Good one! I left you some comments.

2023-06-07 13:08 UTC, doemser commented on components/WorkoutsList/NewWorkoutForm/index.js
> +      ></Input>
inputs type text are self-closing

2023-06-07 14:10 UTC, JohannSiemens commented on components/AddedExercisesList/AddedExercise/openCard/OpenCardForm/index.js
>    }, [data, isLoading]);
I will put this on my list for the refactoring part in the later US, otherwise this one is getting too big.

2023-06-07 14:13 UTC, JohannSiemens commented on components/Typography/index.js
> +};
I couldn't fit in all my styling into this one US, because it would be too big, that's why i prepared the Typography for the upcoming component styling in the next US.

2023-06-07 14:41 UTC, doemser requested changes
Good improvements, only have a few comments left

2023-06-07 14:41 UTC, doemser commented on components/WorkoutsList/NewWorkoutForm/index.js
> +    <Form variant="small" onSubmit={createWorkout}>
Here you are not using the Styled.. prefix, but it is a styled-component only which should get the prefix

2023-06-07 14:41 UTC, doemser commented on styles.js
> +  }
for color variables you could use the ThemeProvider from styled-components ( recommended for your tech-stack )

2023-06-09 09:15 UTC, JohannSiemens commented on styles.js
> +  }
After a quick read of the docs i will put the topic of ThemeProvider on my refactoring list to fully understand what this is doing and how to properly implement it

2023-06-10 06:50 UTC, merged